-- 高级配置字段：SEO / 强调色 / 玻璃卡片 / 脚本注入 / 时钟 / 一言 / 背景遮罩 / 头像
ALTER TABLE "Profile" ADD COLUMN "siteTitle" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Profile" ADD COLUMN "siteDescription" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Profile" ADD COLUMN "siteKeywords" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Profile" ADD COLUMN "accentColor" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Profile" ADD COLUMN "glassOpacity" INTEGER NOT NULL DEFAULT 28;
ALTER TABLE "Profile" ADD COLUMN "glassBlur" INTEGER NOT NULL DEFAULT 16;
ALTER TABLE "Profile" ADD COLUMN "analyticsScript" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Profile" ADD COLUMN "headScript" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Profile" ADD COLUMN "timeFormat" TEXT NOT NULL DEFAULT '24';
ALTER TABLE "Profile" ADD COLUMN "showSeconds" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Profile" ADD COLUMN "dateFormat" TEXT NOT NULL DEFAULT 'YYYY年M月D日 dddd';
ALTER TABLE "Profile" ADD COLUMN "hitokotoType" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Profile" ADD COLUMN "bgOverlay" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Profile" ADD COLUMN "avatarShape" TEXT NOT NULL DEFAULT 'circle';
ALTER TABLE "Profile" ADD COLUMN "avatarBorderColor" TEXT NOT NULL DEFAULT '';
